apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rasa-pvc
  namespace: kauza
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: default  # Adjust based on your cluster's setup