apiVersion: v1
kind: PersistentVolume
metadata:
  name: rasa-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default  # Match this with your PVC
  hostPath:
    path: "/mnt/data/rasa"  # Change this path based on your cluster setup
