profile: auth0|67e4a833d6518eacc30c9a321750157525408
recipe: default.v1
language: en
assistant_id: 20240219-025211-concave-skunk
model: 20250618-144600-[isdi_bot_v2]
models:
- default_filename
- 20250618-144600-['isdi_bot_v2']
pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - number
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  epochs: 100
- name: AugmentedMemoizationPolicy
- name: RulePolicy
